package com.medipro.manager.data.document

import android.content.Context
import android.graphics.Canvas
import android.graphics.Paint
import dagger.hilt.android.qualifiers.ApplicationContext
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class AppVersionProvider @Inject constructor(
    @ApplicationContext private val context: Context,
) {
    val versionName: String
        get() = runCatching {
            context.packageManager.getPackageInfo(context.packageName, 0).versionName
        }.getOrNull()?.takeIf { it.isNotBlank() } ?: "1.1.34"
}

object PdfFooter {
    fun draw(
        canvas: Canvas,
        left: Float,
        pageHeight: Float,
        versionName: String,
        generatedAt: Long = System.currentTimeMillis(),
        paint: Paint,
    ) {
        val formatter = SimpleDateFormat("yyyy-MM-dd HH:mm", Locale.getDefault())
        val lines = listOf(
            "Generated by MediPro ERP",
            "Version $versionName",
            "Generated: ${formatter.format(Date(generatedAt))}",
        )
        var y = pageHeight - 56f
        lines.forEach { line ->
            canvas.drawText(line, left, y, paint)
            y += 14f
        }
    }
}

object PdfWatermark {
    fun draw(canvas: Canvas, pageWidth: Int, pageHeight: Int, text: String) {
        val paint = Paint().apply {
            color = 0x33AAAAAA
            textSize = 72f
            isFakeBoldText = true
            textAlign = Paint.Align.CENTER
        }
        canvas.save()
        canvas.rotate(-35f, pageWidth / 2f, pageHeight / 2f)
        canvas.drawText(text, pageWidth / 2f, pageHeight / 2f, paint)
        canvas.restore()
    }
}
