package com.medipro.manager.data.seed

import android.content.Context
import androidx.room.withTransaction
import com.medipro.manager.core.database.MediProDatabase
import com.medipro.manager.core.database.entity.MedicineEntity
import com.medipro.manager.core.datastore.AppPreferences
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File
import java.io.FileOutputStream
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Loads pre-built seed.db from assets into Room on first launch.
 * seed.db is generated by assets/importer ETL pipeline.
 */
@Singleton
class SeedDataImporter @Inject constructor(
    @ApplicationContext private val context: Context,
    private val database: MediProDatabase,
    private val preferences: AppPreferences,
) {
    suspend fun importIfNeeded() = withContext(Dispatchers.IO) {
        if (preferences.isSeedImported() || database.medicineDao().count() > 0) {
            preferences.setSeedImported()
            return@withContext
        }

        val seedFile = copyAssetDb(ASSET_SEED_DB) ?: return@withContext

        try {
            val seedDb = openReadOnly(seedFile)
            seedDb.rawQuery(
                """
                SELECT uuid, brandName, genericName, composition, strength, dosageForm, manufacturer,
                       category, barcode, unit, purchasePricePaisa, sellingPricePaisa, mrpPaisa,
                       vatPercent, reorderLevel, description, requiresPrescription, controlledSubstance,
                       scheduleCategory, isActive, createdAt, updatedAt, deletedAt, syncStatus, syncVersion, deviceId
                FROM medicines
                """.trimIndent(),
                null
            ).use { cursor ->
                database.withTransaction {
                    val dao = database.medicineDao()
                    while (cursor.moveToNext()) {
                        dao.insert(
                            MedicineEntity(
                                id = 0,
                                uuid = cursor.getString(0),
                                brandName = cursor.getString(1),
                                genericName = cursor.getString(2),
                                composition = cursor.getString(3),
                                strength = cursor.getString(4),
                                dosageForm = cursor.getString(5),
                                manufacturer = cursor.getString(6),
                                category = cursor.getString(7),
                                barcode = cursor.getString(8),
                                unit = cursor.getString(9),
                                purchasePricePaisa = cursor.getLong(10),
                                sellingPricePaisa = cursor.getLong(11),
                                mrpPaisa = cursor.getLong(12),
                                vatPercent = cursor.getDouble(13),
                                reorderLevel = cursor.getInt(14),
                                description = cursor.getString(15),
                                requiresPrescription = cursor.getInt(16) == 1,
                                controlledSubstance = cursor.getInt(17) == 1,
                                scheduleCategory = cursor.getString(18),
                                isActive = cursor.getInt(19) == 1,
                                createdAt = cursor.getLong(20),
                                updatedAt = cursor.getLong(21),
                                deletedAt = cursor.getLong(22).takeIf { !cursor.isNull(22) },
                                syncStatus = cursor.getString(23),
                                syncVersion = cursor.getLong(24),
                                deviceId = cursor.getString(25),
                            )
                        )
                    }
                }
            }
            seedDb.close()
            preferences.setSeedImported()
        } finally {
            seedFile.delete()
        }
    }

    private fun copyAssetDb(assetPath: String): File? = try {
        context.assets.open(assetPath).use { input ->
            val out = File(context.cacheDir, assetPath.substringAfterLast('/'))
            FileOutputStream(out).use { output -> input.copyTo(output) }
            out
        }
    } catch (_: Exception) {
        null
    }

    private fun openReadOnly(file: File) =
        android.database.sqlite.SQLiteDatabase.openDatabase(
            file.absolutePath,
            null,
            android.database.sqlite.SQLiteDatabase.OPEN_READONLY
        )

    companion object {
        const val ASSET_SEED_DB = "databases/seed.db"
    }
}
